version: '3.7'

services:
  db:
    environment:
      POSTGRES_DB: brownline_app
      POSTGRES_USER: brownline
      POSTGRES_PASSWORD: brownline
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch:2.3
    restart: always
    expose:
      - "9200"
  app:
    environment:
      DJANGO_SECRET_KEY: an*it@jjvnuw5qd9kb3b9*tzhigrrphkkw@x_$d_pje+m(2k((
      DATABASE_URL: postgres://brownline:brownline@db/brownline_app
      CACHE_URL: redis://redis
      ELASTICSEARCH_ENDPOINT: elasticsearch
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - media-root:/code/brownline/media
    links:
      - db:db
      - redis:redis
      - elasticsearch:elasticsearch
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - elasticsearch
volumes:
  media-root: